In [6]:
import numpy as np

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [11]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [12]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.random.rand(1)

array([0.51141425])

In [15]:
np.random.randn(25)

array([ 0.07200827, -0.22440414,  0.17557902, -1.24063097, -2.25333136,
        0.2783453 ,  0.8993361 ,  0.79661252, -0.90744808, -0.86046293,
        0.76303416, -0.21805469, -1.26964078, -0.81528335, -1.88902323,
        0.35091251, -1.36624857,  2.30263488, -2.43592512, -0.13560881,
       -0.32170286, -0.25912292,  0.28218315,  0.7728404 ,  1.18811435])

In [16]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [17]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [18]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
import numpy as np
a = np.arange(1,26).reshape(5,5)
a[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [20]:
a[3:4,4]

array([20])

In [21]:
a[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [22]:
a[4:]

array([[21, 22, 23, 24, 25]])

In [23]:
a[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
a[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [25]:
a.sum()

325

In [26]:
a.std()

7.211102550927978

In [27]:
a[0].sum()

15

In [28]:
a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [29]:
import numpy as np
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
b = np.arange(1,17).reshape(4,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
b.dtype

dtype('int32')

In [32]:
c = np.arange(1,13).reshape(3,2,2)
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [33]:
b.shape

(4, 4)

In [34]:
a.shape

(15,)

In [35]:
c.shape

(3, 2, 2)

In [36]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.ones(12).reshape(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
c.ndim

3

In [41]:
maths_marks=np.random.randint(1,100,20)
maths_marks

array([76, 20, 16,  7, 41, 68, 27, 22, 79, 62, 99, 90, 62, 96, 36, 86, 46,
       25, 87, 43])

In [45]:
ass=np.sort(maths_marks)
ass

array([ 7, 16, 20, 22, 25, 27, 36, 41, 43, 46, 62, 62, 68, 76, 79, 86, 87,
       90, 96, 99])

In [47]:
dsc=np.flip(ass)
dsc

array([99, 96, 90, 87, 86, 79, 76, 68, 62, 62, 46, 43, 41, 36, 27, 25, 22,
       20, 16,  7])

In [48]:
e=np.arange(1,26).reshape(5,5)
e
f=e.reshape(25)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [49]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.eye(5).reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [52]:
mat=np.arange(0,9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
np.append(mat,[[9,10,11]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
np.split(mat,3,axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [56]:
v=mat
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
np.split(v,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [63]:
s=np.random.uniform(1,9,10)
s

array([6.02865956, 4.8678502 , 4.19203269, 8.46525875, 1.2316077 ,
       2.6094744 , 2.05818731, 5.33112114, 6.80205968, 1.3230216 ])

In [64]:
np.ceil(s)

array([7., 5., 5., 9., 2., 3., 3., 6., 7., 2.])

In [65]:
np.floor(s)

array([6., 4., 4., 8., 1., 2., 2., 5., 6., 1.])

In [66]:
np.round(s,2)

array([6.03, 4.87, 4.19, 8.47, 1.23, 2.61, 2.06, 5.33, 6.8 , 1.32])

In [68]:
q=np.arange(0,25).reshape(5,5)
q

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
q.min(axis=0)

array([0, 1, 2, 3, 4])

In [70]:
q.max(axis=0)

array([20, 21, 22, 23, 24])

In [71]:
q.std(axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [72]:
q.var(axis=0)

array([50., 50., 50., 50., 50.])

In [76]:
w=np.arange(100,151)
w

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [77]:
np.flip(w)

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [79]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [80]:
l=np.array([1,0,2,0,0,4,0,0])
np.nonzero(1)

(array([0], dtype=int64),)

In [82]:
m=np.ones((10,10))
m[1:-1, 1:-1] = 0
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [90]:
n=np.zeros((8,8) , dtype=int)
n[::2, ::2] = 1
n[1::2, 1::2] = 1
n[:]

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [106]:
n=np.zeros((8,8) , dtype=int)
n[::2,::2]=1
n[1::2,1::2]=1
n

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [84]:
o = np.random.randint(1, 10, (3,3))
p = np.random.randint(1, 10, (3,3))

In [85]:
o+p

array([[ 9, 17,  6],
       [15,  8, 10],
       [14, 16, 14]])

In [86]:
o-p

array([[-1,  1, -2],
       [-1,  2,  8],
       [ 0,  0,  0]])

In [87]:
o*p

array([[20, 72,  8],
       [56, 15,  9],
       [49, 64, 49]])